version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      #HOSTNAME_COMMAND: "$(hostname -i)"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  pipelinedb:
    image: tkanos/pipelinedb_kafka
    ports:
      - "5432:5432"
    links:
      - zookeeper
      - kafka
# don't forget the 127.0.0.1 kafka